config/routes.rb
Rails.application.routes.draw do
  root 'questions#index'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :questions do
    resources :answers
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question

  validates :description, presence: true,
              length: { minimum: 50 }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :answers, dependent: :destroy

  validates :title, presence: true,
              length: { minimum: 20 }

  validates :description, presence: true,
              length: { minimum: 50 }


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  # GET /questions/:question_id/answers/new
  # def new
  # #   puts "in new"
  # #   puts params[:question_id]
  # #   @question = Question.find(params[:question_id])
  # #
  # #   puts @question
  # #   # @answer = @question.answers.new
  #    @answer = Answer.new
  #  end
  # POST /questions/:question_id/answers
  def create
    @question = Question.find(params[:question_id])
    # @answer = @question.answers.new(answers_params)
    @answer = Answer.new(answers_params)
    @answer.question = @question

    if @answer.save
      redirect_to question_path(@question), notice: 'Answer was successfully posted.'
    else
      #notice: msg doesn't work with render
      render '/questions/show'
    end
  end

  private
    def answers_params
      params.require(:answer).permit(:description)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @questions = Question.order(created_at: :desc)
  end

  def show
    @question = Question.find(params[:id])
    @answer = @question.answers.build(params[:answer])
  end

  def new
    @question = Question.new
  end

  def edit
    @question = Question.find(params[:id])
  end

  def create
    @question = Question.new(questions_params)
    if @question.save
      redirect_to @question, notice: 'Question was successfully posted.'
    else
      render 'new'
    end
  end

  def update
    @question = Question.find(params[:id])
    if @question.update(questions_params)
      redirect_to @question, notice: 'Question was successfully updated.'
    else
      render 'edit'
    end
  end

  def destroy
    @question = Question.find(params[:id])
    @question.destroy
    redirect_to questions_path
  end

  private
    def questions_params
      params.require(:question).permit(:title, :description)
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/answers/_answer.html.erb
<% if answer.description %>
  <p><strong>Answer:</strong> <%= answer.description %></p>
<% end %>

app/views/answers/_form.html.erb
<%= form_for [ @question, @answer ] do |f| %>
<% if @answer.errors.any? %>
  <div id="error_explanation">
    <h4>
      <%= pluralize(@answer.errors.count, "error") %> prohibited
      this answer from being posted:
    </h4>
    <ul>
      <% @answer.errors.full_messages.each do |msg| %>
        <li><%= msg.gsub!('Description', 'Answer') %></li>
      <% end %>
    </ul>
  </div>
<% end %>
  <p>

    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.submit "Submit Answer" %>
  </p>
<% end %>

app/views/homes/index.html.erb
<p>
  Modify me in `app/views/homes/index.html.erb` or change the root directive in
  `config/routes.rb`
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RescueMission</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <%= stylesheet_link_tag 'application', media: 'all' %>

    <%= javascript_include_tag "vendor/modernizr" %>

  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="top-bar">
    <ul class="title-area">
      <li class="name">
        <h1><a href="/">RescueMission</a></h1>
      </li>
    </ul>

    <section class="top-bar-section">
      <ul class="right">
        <%- if current_user -%>
          <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
        <%- else -%>
          <li><%= link_to 'Sign Up', new_user_registration_path %></li>
          <li><%= link_to 'Sign In', new_user_session_path %></li>
        <%- end -%>
      </ul>
    </section>
  </nav>
  <div class = "row">
    <%- flash.each do |key, value| -%>
      <div class="flash flash-<%= key %>">
        <%= value %>
      </div>
    <%- end -%>

    <%= yield %>
  </div>
  <%= javascript_include_tag 'application' %>
  <%= yield :extra_footer %>
</body>
</html>

app/views/questions/_form.html.erb
<%= form_with model: @question, local: true do |f| %>
  <% if @question.errors.any? %>
    <div class="error_explanation">
      <h4>
        <%= pluralize(@question.errors.count, "error") %> prohibited
        this question from being posted:
      </h4>
      <ul>
        <% @question.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :title %> <br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.submit @question.persisted? ? "Edit Question" : "Post Question" %>
  </p>
<% end %>

app/views/questions/edit.html.erb
<h2>Edit Question</h2>
<%= render "form" %>
<p>
  <%= link_to 'Delete this Question', question_path(@question),
                method: :delete,
                data: { confirm: 'Are you sure?' } %>
</p>    
<p>
  <%= link_to "Back to Question's page", question_path(@question) %>
<p>
<p>
  <%= link_to "All Questions Listing", questions_path %>
</p>

app/views/questions/index.html.erb
<h2>Questions Listing</h2>
<p>
  <%= link_to 'Post a New Question', new_question_path %>
</p>
<p></p>

<table>
  <% @questions.each do |question| %>
    <tr>
      <td><%= link_to "#{question.title}", question_path(question) %></td>


    </tr>
  <% end %>

</table>

app/views/questions/new.html.erb
<h2>Post a Question</h2>
<%= render "form" %>

app/views/questions/show.html.erb
<!-- <p id="notice"><%= notice %></p> -->
<h2>Question details</h2>
<p>
  <strong>Title:</strong> <%= @question.title %>
</p>
<p>
  <strong>Description:</strong> <%= @question.description %>
</p>

<p>
  <%= link_to "Edit this Question", edit_question_path(@question) %> |
  <%= link_to 'Delete this Question', question_path(@question),
                method: :delete,
                data: { confirm: 'Are you sure?' } %>
</p>

<%= render @question.answers.order(created_at: :asc) %>

<p>Post your Answer:</p>
<%= render '/answers/form' %>

<p>
  <%= link_to "Back to Questions Listing", questions_path %>
</p>